# -*- coding: utf-8 -*-
"""Python project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJ8dKGUctiEQ-vQYxcVhwdnmoNtsVGi5
"""

import random

print(" Welcome to Rock, Paper, Scissors!")
print("Type rock, paper, or scissors to play. Type 'exit' to quit.\n")

choices = ["rock", "paper", "scissors"]

while True:
    user_choice = input("Your choice: ").lower()

    if user_choice == "exit":
        print("Thanks for playing! ")
        break

    if user_choice not in choices:
        print("Invalid choice! Please type rock, paper, or scissors.\n")
        continue

    computer_choice = random.choice(choices)
    print(f"Computer chose: {computer_choice}")

    if user_choice == computer_choice:
        print("It's a tie! \n")
    elif (user_choice == "rock" and computer_choice == "scissors") or \
         (user_choice == "scissors" and computer_choice == "paper") or \
         (user_choice == "paper" and computer_choice == "rock"):
        print("You win! \n")
    else:
        print("You lose! \n")

